// LOCALHOST
###
GET http://localhost:3000/todo
###
GET http://localhost:3000/todo/63d45fc1356bb32a4abea556
###
GET http://localhost:3000/todo/63d45fc1356bb32a4abea557
###
GET http://localhost:3000/todo/63d45fc1356bb32a4abea558
###
POST http://localhost:3000/todo HTTP/1.1 
content-type: application/json

{
    "taskName": "Dishes",
    "taskImportance": "Medium",
    "taskCategory": "Household",
    "taskStartDate": "2/4/2023",
    "taskDueDate": "2/9/2023",
    "taskCompletedDate": "2/29/2023",
    "taskCompletedBy": "Diana"

}

###
POST http://localhost:3000/todo HTTP/1.1 
content-type: application/json

{
    "taskName": "Dishes",
    "taskImportance": "Medium",
    "taskCategory": "Household",
    "taskStartDate": "1/27/2023",
    "taskDueDate": "1/30/2023",
    "taskCompletedDate": "1/29/2023",
    "taskCompletedBy": "Diana"

}

###
PUT http://localhost:3000/todo/63d45fc1356bb32a4abea558 HTTP/1.1 
content-type: application/json

{
    "taskName": "Read C# Homework",
    "taskImportance": "High",
    "taskCategory": "Schoolwork",
    "taskStartDate": "1/27/2023",
    "taskDueDate": "2/12/2023",
    "taskCompletedDate": "2/1/2023",
    "taskCompletedBy": "Diana"

}

###
DELETE http://localhost:3000/todo/63d46876102042c424ab49b4 HTTP/1.1



// PRODUCTION Deploy
###
GET https://cse341-l02.onrender.com/todo
###
GET https://cse341-l02.onrender.com/todo/63d45fc1356bb32a4abea558
###
GET https://cse341-l02.onrender.com/todo/63d45fc1356bb32a4abea557
###
GET https://cse341-l02.onrender.com/todo/63d45fc1356bb32a4abea556

###
POST http://cse341-l02.onrender.com/todo HTTP/1.1 
content-type: application/json

{
    "taskName": "Laundry",
    "taskImportance": "High",
    "taskCategory": "Household",
    "taskStartDate": "2/7/2023",
    "taskDueDate": "2/10/2023",
    "taskCompletedDate": "1/29/2023",
    "taskCompletedBy": "Fred"
}

###
PUT http://cse341-l02.onrender.com/todo HTTP/1.1 
content-type: application/json

{
    "taskName": "Clean Fridge",
    "taskImportance": "High",
    "taskCategory": "Household",
    "taskStartDate": "1/27/2023",
    "taskDueDate": "2/1/2023",
    "taskCompletedDate": "1/29/2023",
    "taskCompletedBy": "Gertrude"
}

###
DELETE http://cse341-l02.onrender.com/todo/63d45fc1356bb32a4abea556 HTTP/1.1